FORMAT: 1A
HOST: http://localhost/loja/xml.php

# API PHP Ecommerce
API destinada ao ecommerce PHP onde plataformas integradoras poderão solicitar acesso para a utilização.

**Note:** Aqui está um exemplo de nota
[Raw](https://raw.github.com/apiaryio/api-blueprint/master/examples/01.%20Simplest%20API.md)

# GET /
+ Response 200 (text/plain)

        Hello World!